#!/bin/bash
MY_PATH="`dirname \"$0\"`"

function pingpong {
	echo 'Welche Adresse soll angesprochen werden?'
	read destination
	ping $destination -c 4
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

while true; do
	clear
	echo '            __  __               __                       '
	echo '           / / / /___ __________/ /      ______ _________ '
	echo '          / /_/ / __ `/ ___/ __  / | /| / / __ `/ ___/ _ \'
	echo '         / __  / /_/ / /  / /_/ /| |/ |/ / /_/ / /  /  __/'
	echo '        /_/ /_/\__,_/_/   \__,_/ |__/|__/\__,_/_/   \___/ '
	echo '                                     ____                   '
	echo '     _   _____  ______      ______ _/ / /___  ______  ____ _'
	echo '    | | / / _ \/ ___/ | /| / / __ `/ / __/ / / / __ \/ __ `/'
	echo '    | |/ /  __/ /   | |/ |/ / /_/ / / /_/ /_/ / / / / /_/ / '
	echo '    |___/\___/_/    |__/|__/\__,_/_/\__/\__,_/_/ /_/\__, /  '
	echo '                                                   /____/   '
	echo 
	uptime
	echo
	echo '  (1) In-/Output Statistik'
	echo '   (2) Virtuelle Speicherstatistik'
	echo '    (3) Netzwerkschnittstellen Statistik'
	echo '     (4) Prozessverwaltung'
	echo '      (5) Ping'
	echo '       (x) exit'
	echo
	read -n 1 selection
	echo -ne "\r" # remove input
	
	case $selection in
		1) 
			iostat
			read -n 1
		;;
		2) 
			vmstat
			read -n 1
		;;
		3) 
			netstat -i
			read -n 1
		;;
		4) $MY_PATH/processmgmt; ;;
		5) pingpong; ;;
		x) 
			exit;
		;;
	esac
done
