#!/bin/bash

function userView {
	title
	echo 'Eingeloggte Nutzer:'
	w
	echo ''
	echo 'Alle Nutzer:'
	cut -d: -f1 /etc/passwd
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupView {
	echo 'Alle Gruppen:'
	cut -d: -f1 /etc/group
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userCreate {
	echo 'Geben Sie den Nutzernamen ein:'
	read username

	echo "Möchten Sie ein Homeverzeichnis für $username erstellen? (J=Ja)"
	read -n 1 homedir
	if [ ${homedir^^} == "J" ]; then
		useradd $username -m
	else
		useradd $username
	fi
	passwd $username
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userChangeName {
	echo "Geben Sie den neuen Nutzernamen für $1 ein:"
	read newusername

	usermod -l $newusername $1
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userChangePassword {
	passwd $username
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1	
}

function userChangeNewHome {
	echo 'Geben Sie den Pfad für das neue Home-Verzeichnis ein:'
	read directory
	if [ -d "$directory" ]; then
	echo 'Soll der Inhalt des aktuellen Home-Verzeichnisses in das neue Home-Verzeichnis verschoben werden? (J=Ja)'
	read moveHome -n 1
	echo -ne "\r" # remove input

		if [ ${moveHome^^} == "J" ]; then
			usermod -d $directory -m $1
		else
			usermod -d $directory $1
		fi
	fi
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userAddGroup {
	userListGroups $1
	echo "Welcher Gruppe soll $1 hinzugefügt werden?"
	read group
	usermod -a -G $group $1
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userRemoveGroup {
	userListGroups $1
	echo "Welcher Gruppe soll $1 entfernt werden?"
	read group
	deluser --group $1 $group
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userListGroups {
	echo "Aktuelle Gruppen von $1:"
	groups $1	
}

function userChange {
	echo 'Geben Sie den aktuellen Nutzernamen ein:'
	read username
	
	if id "$username" >/dev/null 2>&1; then
		echo "Was möchten Sie für $username ändern?"
		echo '  (1) Nutzername'
		echo '   (2) Passwort'
		echo '    (3) Neues Homeverzeichnis'
		echo '     (4) Gruppenzugehörigkeit hinzufügen'
		echo '      (5) Gruppenzugehörigkeit entfernen'

		read -n 1 selection
		echo -ne "\r" # remove input

		case $selection in
		1) userChangeName $username; ;;
		2) userChangePassword $username; ;;
		3) userChangeNewHome $username; ;;
		4) userAddGroup $username; ;;
		5) userRemoveGroup $username; ;;
		esac
	else
		echo 'Nutzer existiert nicht!'
	fi
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function userDelete {
	echo 'Geben Sie den Nutzernamen des zu löschenden Nutzers ein:'
	read delusername

	echo 'Möchten Sie das Home-Verzeichnis und den Mailspool entfernen? (J=Ja)'
	read delhome
	if [ ${delhome^^} == "J" ]; then
		userdel -r $delusername
	else
		userdel $delusername
	fi
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupCreate {
	echo 'Geben Sie den Gruppennamen ein:'
	read groupname

	echo 'Möchten Sie ein Passwort für die Gruppe festlegen? (J=Ja)'
	read password

	groupadd $groupname
	if [ ${password^^} == "J" ]; then
		gpasswd $groupname
	fi
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupChangeName {
	echo "Geben Sie den neuen Gruppennamen für $1 ein:"
	read newGroupName
	
	groupmod -n $newGroupName $1
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupChangePassword {
	gpasswd $1
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupChange {
	echo 'Geben Sie den Gruppennamen ein:'
	read groupname

	if grep ^$groupname: /etc/group >/dev/null 2>&1; then
		echo "Was möchten Sie für $groupname ändern?"
			echo '  (1) Gruppennamen'
			echo '   (2) Passwort'
			read -n 1 selection
			echo -ne "\r" # remove input

			case $selection in
			1) groupChangeName $groupname; ;;
			2) groupChangePassword $groupname; ;;
			esac
	else
		echo "Gruppe $groupname existiert nicht!"
	fi
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

function groupDelete {
	echo 'Geben Sie den Gruppennamen der zu löschenden Gruppe ein:'
	read groupname

	groupdel $groupname
	echo ">>> Zurück zum Menü, irgendeine Taste drücken <<<"
	read -n 1
}

while true; do
	clear
	echo
	echo '            ____                   __                 '
	echo '           / __ )___  ____  __  __/ /_____  ___  _____'
	echo '          / __  / _ \/ __ \/ / / / __/_  / / _ \/ ___/'
	echo '         / /_/ /  __/ / / / /_/ / /_  / /_/  __/ /    '
	echo '        /_____/\___/_/ /_/\__,_/\__/ /___/\___/_/     '
	echo '                                     ____                   '
	echo '     _   _____  ______      ______ _/ / /___  ______  ____ _'
	echo '    | | / / _ \/ ___/ | /| / / __ `/ / __/ / / / __ \/ __ `/'
	echo '    | |/ /  __/ /   | |/ |/ / /_/ / / /_/ /_/ / / / / /_/ / '
	echo '    |___/\___/_/    |__/|__/\__,_/_/\__/\__,_/_/ /_/\__, /  '
	echo '                                                   /____/   '
	echo 
	echo '  (1) Benutzerübersicht'
	echo '   (2) Gruppenübersicht'
	echo '    (3) Benutzer erstellen'
	echo '     (4) Benutzer ändern'
	echo '      (5) Benutzer löschen'
	echo '       (6) Gruppe erstellen'
	echo '        (7) Gruppe ändern'
	echo '         (8) Gruppe löschen'
	echo '          (x) exit'
	echo
	read -n 1 selection
	echo -ne "\r" # remove input
	
	case $selection in
		1) userView; ;;
		2) groupView; ;;
		3) userCreate; ;;
		4) userChange; ;;
		5) userDelete; ;;
		6) groupCreate; ;;
		7) groupChange; ;;
		8) groupDelete; ;;
		x) 
			exit;
		;;
	esac
done
